name: Zirhli Kesintisiz Yayin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

permissions:
  actions: write

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: FFmpeg Kurulumu
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Yayini Aktar (Tam Kamuflaj ve Ses Senkronu)
        run: |
          M3U8_LINK="https://zeustv32321.info/live/b1/playlist.m3u8"
          RTMP="rtmps://dc4-1.rtmp.t.me/s/3701970960:0jSLVLkjAiuVx6F6kI_rhQ"
          
          echo "Yayin Telegram'a basliyor..."
          END_TIME=$((SECONDS+19800))
          
          while [ $SECONDS -lt $END_TIME ]; do
              echo "FFmpeg devrede... Ses senkronizasyon ayarlari aktif!"
              
              # YENİLİKLER: 
              # -fflags +genpts : Zaman damgalarini (PTS) onarir.
              # -af "aresample=async=1" : Sesi videoya milisaniyelik hizalar.
              
              ffmpeg -re -fflags +genpts -headers "Origin: https://zeustv32321.info" -headers "Referer: https://zeustv32321.info/" -headers "Accept: */*" -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 5 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -i "$M3U8_LINK" -c:v copy -c:a aac -af "aresample=async=1" -b:a 128k -ar 44100 -f flv -flvflags no_duration_filesize "$RTMP" || true
              
              echo "Baglanti koptu! 3 saniye icinde tekrar baslatiliyor..."
              sleep 3
          done

      - name: Sistemi Yeniden Tetikle
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Sure doldu! Sistem yenileniyor..."
          gh workflow run "Zirhli Kesintisiz Yayin" --repo ${{ github.repository }} || true
